/* FORMAT FOR TEAMS
{
  'moco_or_mofo': 'mofo',
  'team_name':    'webmaker', // all lower case, no spaces
  'repos': [      'mozilla/appmaker-components',
                  'mozilla/bucheron']
}
 */

exports.teamsRepos = [
  {
  'moco_or_mofo': 'mofo',
  'team_name':    'webmaker',
  'repos': [      'mozilla/appmaker-components',
                  'mozilla/bucheron',
                  'mozilla/butter',
                  'mozilla/csp-logger',
                  'mozilla/eoy-fundraising',
                  'mozilla/events.webmaker.org',
                  'mozilla/friendlycode',
                  'mozilla/Gallery-Maker',
                  'mozilla/goggles.webmaker.org',
                  'mozilla/hookshot',
                  'mozilla/htmlsanitizer.org',
                  'mozilla/login.webmaker.org',
                  'mozilla/lumberyard',
                  'mozilla/make-valet',
                  'mozilla/make.mozilla.org',
                  'mozilla/makeapi-client',
                  'mozilla/makeapi-docs',
                  'mozilla/MakeAPI-Gallery',
                  'mozilla/MakeAPI',
                  'mozilla/makedrive',
                  'mozilla/makerstrap',
                  'mozilla/nav-global',
                  'mozilla/node-hubble',
                  'mozilla/node-rtltr',
                  'mozilla/node-webmaker-butler',
                  'mozilla/node-webmaker-i18n',
                  'mozilla/node-webmaker-loginapi',
                  'mozilla/node-webmaker-postalservice',
                  'mozilla/park-warden',
                  'mozilla/popcorn_maker',
                  'mozilla/popcorn-docs',
                  'mozilla/popcorn-js',
                  'mozilla/popcorn.webmaker.org',
                  'mozilla/popcornjs.org',
                  'mozilla/sawmill',
                  'mozilla/teach-appmaker',
                  'mozilla/thimble.webmaker.org',
                  'mozilla/togetherjs',
                  'mozilla/web-literacy-client',
                  'mozilla/webliteracystandard',
                  'mozilla/webmaker-analytics',
                  'mozilla/webmaker-auth-client',
                  'mozilla/webmaker-auth',
                  'mozilla/webmaker-code-of-conduct',
                  'mozilla/webmaker-download-locales',
                  'mozilla/webmaker-events-2',
                  'mozilla/webmaker-events-service',
                  'mozilla/webmaker-events',
                  'mozilla/webmaker-firehose',
                  'mozilla/webmaker-kits',
                  'mozilla/webmaker-kits-builder',
                  'mozilla/webmaker-language-picker',
                  'mozilla/webmaker-login-example',
                  'mozilla/webmaker-mediasync',
                  'mozilla/webmaker-profile-service',
                  'mozilla/webmaker-profile',
                  'mozilla/webmaker-profile-2',
                  'mozilla/Webmaker-Prototypes',
                  'mozilla/webmaker-suite',
                  'mozilla/webmaker-tests',
                  'mozilla/webmaker-translation-stats',
                  'mozilla/webmaker-ui',
                  'mozilla/webmaker.org',
                  'mozilla-appmaker/appmaker',
                  'mozilla-appmaker/ceci',
                  'mozilla-appmaker/ceci-button',
                  'mozilla-appmaker/ceci-fork-me',
                  'mozilla-appmaker/ceci-support',
                  'mozilla-appmaker/chefbot',
                  'mozilla-appmaker/component-addform',
                  'mozilla-appmaker/component-alternating-gate',
                  'mozilla-appmaker/component-button',
                  'mozilla-appmaker/component-button-with-confirmation',
                  'mozilla-appmaker/component-camera-button',
                  'mozilla-appmaker/component-chat-window',
                  'mozilla-appmaker/component-counter',
                  'mozilla-appmaker/component-dataview',
                  'mozilla-appmaker/component-editform',
                  'mozilla-appmaker/component-fireworks',
                  'mozilla-appmaker/component-header',
                  'mozilla-appmaker/component-image',
                  'mozilla-appmaker/component-metronome',
                  'mozilla-appmaker/component-paypal',
                  'mozilla-appmaker/component-spacer',
                  'mozilla-appmaker/component-splitter',
                  'mozilla-appmaker/component-template',
                  'mozilla-appmaker/component-text-input',
                  'mozilla-appmaker/component-textbox',
                  'mozilla-appmaker/dashboard',
                  'mozilla-appmaker/haas',
                  'mozilla-appmaker/mozilla-appmaker.github.io',
                  'mozilla-appmaker/phonegap-appmaker-harness',
                  'mozilla-appmaker/start-here',
                  'mozilla-appmaker/tools',
                  'mozilla-appmaker/views']
  },
  {
    'moco_or_mofo': 'mofo',
    'team_name':    'opennews',
    'repos': [      'mozilla/mozilla-opennews',
                    'mozilla/source']
  },
  {
    'moco_or_mofo': 'moco',
    'team_name':    'qa',
    'repos': [      'mozilla/fxa-auth-server',
                    'mozilla/fxa-content-server',
                    'mozilla/fxa-js-client',
                    'mozilla-services/pushgo',
                    'mozilla-services/puppet-config',
                    'mozilla-services/svcops-oompaloompas',
                    'mozilla-b2g/gaia',
                    'mozilla/gecko-dev']
  }
];
